---
- name: restart and enable tomcat and firewalld service
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - tomcat
    - firewalld
  listen: "Enable and Restart"

- name: open port 8080
  firewalld: 
    port: "{{ tomcatport }}"
    permanent: yes
    state: enabled
    immediate: yes
    zone: public
  listen: "Enable and Restart"
