---
- name: Install tomcat
  yum: 
   name: ['tomcat','tomcat-webapps','tomcat-admin-webapps']
   state: latest

- name: Copy tomcat users file
  copy:
   src: tomcat-users.xml
   dest: /usr/share/tomcat/conf/tomcat-users.xnl
   force: yes
  notify: "trigger handler"