---
- name: Restart tomcat and firewalld service
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
   - tomcat
   - firewalld
  listen: "enable and restart"

- name: Open port 8080
  firewalld:
    port: "{{ tomcatport }}"
    state: enabled
    permanent: yes
    zone: public
    immediate: yes
  listen: "enable and restart"