---
- name: To showcase when_items
  hosts: all
  become: true
  tasks:
   - name: Restart services
     service:
       name: "{{ item }}"
       state: restarted
     with_items:
      - docker
      - httpd
      - postfix
